import './globals.css'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className='overflow-x-hidden bg-white'>
                <main className='max-w-[1200px] mx-auto px-4 xl:px-0'>{children}</main>
            </body>
        </html>
    )
}
